### ISSUE TITLE
`meta[name=viewport]` present in the reflowable test

### ISSUE THREAD

**Issue by ghost** [readium/readium-test-files#7]
In the test for reflowable content @`readium-test-files/functional/smoke-tests/SmokeTestFXL/xhtml/epub-layout-007.xhtml` there is a `<meta name="viewport" content="width=576, height=1024"/>` in the `<html>`.

Is that normal or is it a mistake?

**Comment by rkwright** [comment]
Yes, this is correct as it is fixed-layout file.
